apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadgndc9286-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadgndc9286-tenant-component
    app.kubernetes.io/part-of: loadgndc9286-tenant-app
  name: loadgndc9286-tenant-component
  namespace: loadgndc9286-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadgndc9286-tenant-component
    weight: null
status: {}
